services:
  api:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: petradar
      DB_SYNC: "true"
      PORT: 3001
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: "6379"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=fde0db05-b150-4b42-aedb-590cb6b14d48;IngestionEndpoint=https://mexicocentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://mexicocentral.livediagnostics.monitor.azure.com/;ApplicationId=916b1f56-eaa4-4153-af7e-85f233eebc12"
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: petradar
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d petradar"]
      interval: 5s
      timeout: 5s
      retries: 20
